name: econ-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy=1.13
  - pandas=2.2
  - polars
  - statsmodels=0.14
  - matplotlib=3.8
  - seaborn=0.13
  - scikit-learn=1.5
  - xgboost
  - lightgbm
  - pytorch=2.4.*
  - contourpy
  - kiwisolver
  - pillow
  - fonttools

  - ipykernel
  - pandoc
  - quarto

  - r-base=4.3.*
  - r-essentials
  - r-tidyverse
  - r-data.table
  - r-fixest
  - r-did
  - r-bacondecomp
  - r-matchit
  - r-cobalt
  - r-grf
  - r-tidymodels
  - r-mlogit
  - r-fable
  - r-vars
  - r-urca
  - r-prophet
  - r-modelsummary
  - r-ggplot2
  - r-rvest
  - r-languageserver

  - pip

